keys:
  - &noir age1agdx2gn9dm8s6gvsevlpa5agaamgvmtfq7rvh8t2725gqzmaka5qgda2g8
  - &zinc age12pc2l7dyq0tlj0mm56vrwez6yr8nlve6vrucexf7x92dg7qlzcxskrf2tv
  - &vm age1aruj7g3pugj3knq2f5u02tzq6vu5edcjv25veudrsvtr2yzedpusssscpz
creation_rules:
  - path_regex: secrets/[^/]+(\.(yaml|json|env|ini|conf))?$
    key_groups:
      - age:
          - *noir
          - *zinc
          - *vm
