# This file is generated by nixos-generate-config; do not edit!
# To generate this file for your hardware, run:
#   nixos-generate-config --show-hardware-config > hardware-configuration.nix

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # EXAMPLE - Replace with your actual hardware configuration
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ]; # or "kvm-intel" for Intel CPUs
  boot.extraModulePackages = [ ];

  # EXAMPLE - Replace with your actual filesystem configuration
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/CHANGEME-ROOT-UUID";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/CHANGEME-BOOT-UUID";
    fsType = "vfat";
  };

  # Enable swap if needed
  # swapDevices = [
  #   { device = "/dev/disk/by-uuid/CHANGEME-SWAP-UUID"; }
  # ];

  # Enables DHCP on each ethernet and wireless interface
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux"; # or "aarch64-linux" for ARM
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware; # or hardware.cpu.intel
}