---
# inspo: https://github.com/reckenrode/nixos-configs/blob/main/.github/workflows/main.yml
name: Bump flake.lock
on:
  schedule:
    # 10am UTC is 3am PDT/2am PST
    - cron: 0 10 * * *
  workflow_dispatch: null
jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/install-nix-action@v31

      - name: Update flake.lock
        run: nix flake update

      - name: Test updated configurations with Dagger
        uses: dagger/dagger-for-github@v6
        with:
          version: "0.18.16"
          verb: call
          args: test-all-nix-o-s-configurations --source=.

      - name: Commit updated flake.lock
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(deps): bump flake.lock"
          commit_user_name: Flake Bot
          commit_options: --no-verify --signoff
          commit_author: Flake Bot <actions@github.com>
          branch: main
          file_pattern: flake.lock
          skip_dirty_check: false
          skip_fetch: true
