---
# inspo: https://github.com/LGUG2Z/nixos-wsl-starter/blob/master/.github/workflows/build.yml
name: "Release custom WSL tarball and NixOS ISO"
on:
  push:
    tags:
      - v*
  workflow_dispatch: null
jobs:
  # Run full pipeline validation first
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Dagger
        uses: dagger/dagger-for-github@v6
        with:
          version: "0.18.16"

      - name: Run full pipeline validation
        run: dagger call hello --name="Release Validation"

  build:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Dagger
        uses: dagger/dagger-for-github@v6
        with:
          version: "0.18.16"

      - uses: cachix/install-nix-action@v31

      # WSL tarball build disabled - no WSL machines configured
      # - name: Build WSL tarball with Dagger validation
      #   run: |
      #     # First validate with Dagger
      #     dagger call hello --name="WSL Build"
      #     # Then build the tarball (workchng machine removed)
      #     nix_bin=$(which nix)
      #     sudo $nix_bin run .#nixosConfigurations.MACHINE.config.system.build.tarballBuilder

      - name: Build NixOS ISO with Dagger validation
        run: |
          dagger call hello --name="ISO Build"
          # Build ISO using Nix instead of Dagger for now
          nix_bin=$(which nix)
          sudo $nix_bin build .#nixosConfigurations.iso1chng.config.system.build.isoImage
          sudo mv result/iso/nixos-*.iso nixos.iso

      # WSL tarball upload disabled - no WSL machines configured
      # - name: Upload tarball
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: nixos-wsl.tar.gz
      #     path: nixos-wsl.tar.gz

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: nixos.iso
          path: nixos.iso

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            nixos.iso
          body: |
            ## 🚀 Release Notes
            
            This release includes:
            - ✅ Validated NixOS configurations for all machines
            - ✅ Custom NixOS installation ISO (nixos.iso)
            - ✅ Security scanning passed
            - ✅ Full Dagger pipeline validation
            
            ### Machine Configurations Tested
            - **NixOS**: noir, zinc, iso1chng
            - **macOS**: mair, stud
            
            ### Services Included
            - **Active**: NAS (noir), Tailscale (noir, zinc)
            - **Secrets**: SOPS-based encryption with age keys
            - **Security**: Impermanence, SSH hardening, auto-updates
